lib/rewarder_web/router.ex
defmodule RewarderWeb.Router do
  use RewarderWeb, :router

  import RewarderWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {RewarderWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RewarderWeb do
    pipe_through [:browser, :redirect_if_admin_to_index]
    get "/", PageController, :index
    post "/", PageController, :transfer
  end
  scope "/admin", RewarderWeb do
    pipe_through [:browser, :require_authenticated_admin]
    post "/update", PageController, :update
    get "/", PageController, :admin_index
  end

  scope "/prizes", RewarderWeb do
    pipe_through [:browser, :redirect_if_admin_to_rewards]
    get "/history", PrizeController, :history
    get "/acquire/:id", PrizeController, :acquire
    get "/", PrizeController, :index
  end

  scope "/admin_prizes", RewarderWeb do
    pipe_through [:browser, :require_authenticated_admin]
    post "/month_history", PrizeController, :history_by_month
    get "/month_history", PrizeController, :history_by_month
    get "/", PrizeController, :admin_index
    get "/:id/edit", PrizeController, :edit
    get "/new", PrizeController, :new
    post "/", PrizeController, :create
    patch "/:id", PrizeController, :update
    put "/:id", PrizeController, :update
    delete "/:id", PrizeController, :delete
    get "/turn_off/:id", PrizeController, :turn_prize_off
    get "/turn_on/:id", PrizeController, :turn_prize_on
  end
  # Other scopes may use custom stacks.
  # scope "/api", RewarderWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: RewarderWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", RewarderWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", RewarderWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", RewarderWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/rewarder_web/views/layout_view.ex
defmodule RewarderWeb.LayoutView do
  use RewarderWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/rewarder_web/templates/layout/_user_menu.html.heex
<div class="container-fluid">
  <div class="row">
    <nav class="navbar py-2 shadow-sm" style="background-color: #5cdb95;">
      <div class="col-md-3 text-center">
        <%= link to: Routes.page_path(@conn, :index), style: "text-decoration: none;" do %>
        <span class="text-dark h1 nav-item nav-link">Rewarder</span>
        <% end %>
      </div>
        <%= if @current_user do %>
          <div class="col-md-2">
            <ul class="nav flex-column">
            <li class="nav-item">Logged as: <%= @current_user.name %> <%= @current_user.surname %></li> 
            <%= if  @current_user.role != "admin" do %>
            <li class="nav-item">Points you have: <%= @conn.private.plug_session["gathered"] %></li>
              <li class="nav-item">Points you can give: <%= @conn.private.plug_session["to_give"] %></li> 
            <% end %>
            </ul>
          </div>
          
          <div class="col-md-6">
          <%= link to: Routes.prize_path(@conn, :index), style: "text-decoration: none;" do %>
            <span class="text-dark h4 btn btn-secondary">Rewards</span>
          <% end %>
          <%= if @current_user.role == "admin" do %>
            <%= link to: Routes.prize_path(@conn, :history_by_month), style: "text-decoration: none;" do %>
              <span class="text-dark h4 btn btn-secondary">Rewards history by month</span>
            <% end %>
          <% else %>
            <%= link to: Routes.prize_path(@conn, :history), style: "text-decoration: none;" do %>
              <span class="text-dark h4 btn btn-secondary">Your rewards history</span>
            <% end %>
          <% end %>
          <%= link to: Routes.user_settings_path(@conn, :edit), style: "text-decoration: none;" do %>
            <span class="text-dark h4 btn btn-secondary" >Settings</span>
          <% end %>
            <%= link to: Routes.user_session_path(@conn, :delete), method: :delete, style: "text-decoration: none;" do %>
              <span class="text-dark h4 btn btn-secondary">Log out</span>
            <% end %>
          </div>
        <% else %>
        <div class="col-md-6 text-end">
          <%= link to: Routes.user_registration_path(@conn, :new), style: "text-decoration: none;" do %>
            <span class="text-dark h4 btn btn-secondary">Register</span>
          <% end %>
          <%= link to: Routes.user_session_path(@conn, :new), style: "text-decoration: none;" do %>
            <span class="text-dark h4 btn btn-secondary">Log in</span>
          <% end %>
        </div> 
        <% end %>
        <div class="col-md-1"></div>
    </nav>
  </div>
</div>

lib/rewarder_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info bg-primary" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/rewarder_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/rewarder_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Rewarder", suffix: " · Phoenix Framework" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body style="background-color: #edf5e1;">
  <%= render "_user_menu.html", assigns %>
    <div class="container-fluid h-100">
    <%= @inner_content %>
  </div>
  </body>
</html>